// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Features.Categories.Commands.UpsertCategoryCommand.UpsertCategoryCommandHandler.Handle(CT.Application.Features.Categories.Commands.UpsertCategoryCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{CT.Application.Abstractions.Models.BaseOutput{CT.Application.Features.Categories.Commands.UpsertCategoryCommand.UpsertCategoryResponseModel}}")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Features.Gadgets.Commands.DecreaseGadgetStockQuantityCommand.DecreaseGadgetStockQuantityCommandHandler.Handle(CT.Application.Features.Gadgets.Commands.DecreaseGadgetStockQuantityCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{CT.Application.Abstractions.Models.BaseOutput{CT.Application.Features.Gadgets.Commands.DecreaseGadgetStockQuantityCommand.DecreaseGadgetStockQuantityResponseModel}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Services.IdentityServerService.BasicRegisterUserAsync(System.String,System.String,System.String)~System.Threading.Tasks.Task{CT.Application.Models.RegisterUserResponse}")]
[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Features.Gadgets.Commands.UpsertGadgetCommand.UpsertGadgetCommandHandler.Handle(CT.Application.Features.Gadgets.Commands.UpsertGadgetCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{CT.Application.Abstractions.Models.BaseOutput{CT.Application.Features.Gadgets.Commands.UpsertGadgetCommand.UpsertGadgetResponseModel}}")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Features.Gadgets.Commands.IncreaseGadgetStockQuantityCommand.IncreaseGadgetStockQuantityCommandHandler.Handle(CT.Application.Features.Gadgets.Commands.IncreaseGadgetStockQuantityCommand,System.Threading.CancellationToken)~System.Threading.Tasks.Task{CT.Application.Abstractions.Models.BaseOutput{CT.Application.Features.Gadgets.Commands.IncreaseGadgetStockQuantityCommand.IncreaseGadgetStockQuantityResponseModel}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use the 'StringComparison' method overloads to perform case-insensitive string comparisons", Justification = "<Pending>", Scope = "member", Target = "~M:CT.Application.Services.IdentityServerService.BasicUserLoginAsync(System.String,System.String)~System.Threading.Tasks.Task{CT.Application.Models.LoginUserResponse}")]
