/**
 * Clear Treasury - Gadgets API
 *
 * Contact: support@ct.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BasicRegisterUserCommandResponseModel { 
    userIdentifier?: string;
    token?: string;
    refreshToken?: string;
    message?: string;
    result?: BasicRegisterUserCommandResponseModel.ResultEnum;
    resultDescription?: string;
}
export namespace BasicRegisterUserCommandResponseModel {
    export const ResultEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


