/**
 * Clear Treasury - Gadgets API
 *
 * Contact: support@ct.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCategoriesQueryResponseModel } from './getCategoriesQueryResponseModel';


export interface GetEntitiesResponseGetCategoriesQueryResponseModel { 
    totalRecordCount?: number;
    pageIndex?: number;
    pageSize?: number;
    result?: GetEntitiesResponseGetCategoriesQueryResponseModel.ResultEnum;
    message?: string;
    error?: object;
    model?: Array<GetCategoriesQueryResponseModel>;
}
export namespace GetEntitiesResponseGetCategoriesQueryResponseModel {
    export const ResultEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1,
        NUMBER_2: 2,
        NUMBER_3: 3,
        NUMBER_4: 4,
        NUMBER_5: 5,
        NUMBER_6: 6,
        NUMBER_7: 7,
        NUMBER_8: 8,
        NUMBER_9: 9
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


