/**
 * Clear Treasury - Gadgets API
 *
 * Contact: support@ct.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetGadgetCategoryByIdQueryResponseModel { 
    id?: string;
    gadgetId?: string;
    categoryId?: string;
    ordinal?: number;
    createdAt?: string;
    updatedAt?: string;
}

