/**
 * Clear Treasury - Gadgets API
 *
 * Contact: support@ct.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetGadgetByIdQueryResponseModel { 
    id?: string;
    name?: string;
    description?: string;
    stockQuantity?: number;
    createdAt?: string;
    updatedAt?: string;
    lastModifiedByUserId?: string;
    lastModifiedByUserDisplayName?: string;
}

